local M = {}

M.language_to_filetype = function(language)
    if language == vim.NIL then
        return 'md'
    end

    local map = {
        ['ASP.NET'] = 'aspx',
        ['ActionScript'] = 'as',
        ['Ada'] = 'ada',
        ['Apex'] = 'cls',
        ['Arduino'] = 'ino',
        ['Assembly'] = 'asm',
        ['AutoHotkey'] = 'ahk',
        ['Bash'] = 'sh',
        ['Batchfile'] = 'bat',
        ['C#'] = 'cs',
        ['C'] = 'c',
        ['C++'] = 'cpp',
        ['CSS'] = 'css',
        ['Clojure'] = 'clj',
        ['CoffeeScript'] = 'coffee',
        ['D'] = 'd',
        ['Dart'] = 'dart',
        ['Dockerfile'] = 'dockerfile',
        ['Elixir'] = 'ex',
        ['Erlang'] = 'erl',
        ['F#'] = 'fs',
        ['Fortran'] = 'f90',
        ['GLSL'] = 'glsl',
        ['Go'] = 'go',
        ['Gradle'] = 'gradle',
        ['GraphQL'] = 'graphql',
        ['Groovy'] = 'groovy',
        ['HTML'] = 'html',
        ['Handlebars'] = 'hbs',
        ['Haskell'] = 'hs',
        ['Haxe'] = 'hx',
        ['Java'] = 'java',
        ['JavaScript'] = 'js',
        ['Julia'] = 'jl',
        ['Jupyter Notebook'] = 'ipynb',
        ['Kotlin'] = 'kt',
        ['LaTeX'] = 'tex',
        ['Less'] = 'less',
        ['Lisp'] = 'lisp',
        ['Lua'] = 'lua',
        ['MATLAB'] = 'm',
        ['Makefile'] = 'mk',
        ['Markdown'] = 'md',
        ['Nim'] = 'nim',
        ['Nix'] = 'nix',
        ['OCaml'] = 'ml',
        ['Objective-C'] = 'm',
        ['Objective-C++'] = 'mm',
        ['PHP'] = 'php',
        ['Pascal'] = 'pas',
        ['Perl'] = 'pl',
        ['PowerShell'] = 'ps1',
        ['Prolog'] = 'pl',
        ['PureScript'] = 'purs',
        ['Python'] = 'py',
        ['R'] = 'r',
        ['Racket'] = 'rkt',
        ['Roff'] = 'roff',
        ['Ruby'] = 'rb',
        ['Rust'] = 'rs',
        ['SCSS'] = 'scss',
        ['SQL'] = 'sql',
        ['Sass'] = 'sass',
        ['Scala'] = 'scala',
        ['Scheme'] = 'scm',
        ['Shell'] = 'sh',
        ['Smalltalk'] = 'st',
        ['Solidity'] = 'sol',
        ['Stylus'] = 'styl',
        ['Svelte'] = 'svelte',
        ['Swift'] = 'swift',
        ['TCL'] = 'tcl',
        ['TOML'] = 'toml',
        ['TSQL'] = 'sql',
        ['Terraform'] = 'tf',
        ['TypeScript'] = 'ts',
        ['VBScript'] = 'vbs',
        ['VHDL'] = 'vhd',
        ['Vala'] = 'vala',
        ['Verilog'] = 'v',
        ['Vim script'] = 'vim',
        ['Visual Basic .NET'] = 'vb',
        ['WebAssembly'] = 'wasm',
        ['XML'] = 'xml',
        ['YAML'] = 'yml',
        ['Zig'] = 'zig',
    }

    return map[language] or language:lower()
end

return M
